name: Test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make script executable
        run: chmod +x ../../ops/bin/test.sh
      - name: Run tests
        run: ../../ops/bin/test.sh
        
